### ISSUE TITLE
pymobiledevice 3 error

### ISSUE THREAD

**Issue by Majhool** [jawshoeadan/AlpineJitVM#2]
```
Loading Linux virt ...Loading Linux virt ...

Loading initial ramdisk ...Loading initial ramdisk ...


Welcome to Alpine Linux 3.20
Kernel 6.6.49-0-virt on an x86_64 (/dev/ttyS0)

localhost login: root
Password: 
Welcome to Alpine!

The Alpine Wiki contains a large amount of how-to guides and general
information about administrating Alpine systems.
See <https://wiki.alpinelinux.org/>.

You can setup the system with the command: setup-alpine

You may change this message by editing /etc/motd.

localhost:~# ./JitStreamer.sh 
Welcome to JitStreamer!
Starting the server. This might take a few seconds...
This will be your server IP: 100.102.100.70
Traceback (most recent call last):
  File "/root/venv/bin/JitStreamer", line 5, in <module>
    from JitStreamer.__main__ import start_server
  File "/root/venv/lib/python3.12/site-packages/JitStreamer/__init__.py", line 16, in <module>
    from pymobiledevice3.remote.common import TunnelProtocol
ImportError: cannot import name 'TunnelProtocol' from 'pymobiledevice3.remote.common' (/root/venv/lib/python3.12/site-packages/pymobiledevice3/remote/common.py)
localhost:~# 
```

**Comment by h4rqq** [comment]
Getting the same error

**Comment by jawshoeadan** [comment]
Sorry for the delay, try the latest version and see if it works for you.
